name: build-testing-packaging yml
run-name: ${{ github.actor }} Build-Testing-Packaging on Push Workflow
on: [push]

jobs:
#*********************************************
  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - name: Install Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Install Dependencies 
        run: | 
          sudo apt-get install -y stockfish xvfb
      - name: Build project
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" make build
#*********************************************
  test:
    name: "Test"
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - name: Install Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Install Dependencies
        run: | 
          sudo apt-get install -y stockfish xvfb
      - name: Test project
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" make test
#*********************************************
  build-deb:
    name: "Build Debian Package"
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - name: Install Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Install Dependencies
        run: | 
          sudo apt-get install -y stockfish xvfb
      - name: Build deb
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" make build-deb
      - name: Save JAR file
        uses: actions/upload-artifact@v4
        with:
          name: chess jar
          path: p2pChess/target/*.jar
      - name: Save DEB file
        uses: actions/upload-artifact@v4
        with:
          name: chess deb
          path: *.deb
#*********************************************
  lint-debian-package:
    name: "Lint Debian Package"
    needs: build-deb
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - name: Lint Debian Package
        run: |
          sudo apt-get install -y lintian
          make lint-deb
      - run: echo "${{ job.status }}."
